"use client";
import { CreateDispatchPlan$Params } from "@/lib/commands/CreateDispatchPlan/typing";
import { MenuItem, Select } from "@mui/material";
import React from "react";
import DatePicker from "react-datepicker";

type Props = {
  isOpen: boolean;
  onClose: () => void;
  onSave: (params: CreateDispatchPlan$Params) => Promise<void>;
};

const AddSchedulePopup = ({ isOpen, onClose, onSave }: Props) => {
  const [date, setDate] = React.useState<Date | null>();
  const [isAutoGenerated, setIsAutoGenerated] = React.useState("false");

  // Don't render if popup is not open
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-brand-BADFCD rounded-2xl shadow-2xl w-full max-w-2xl mx-4">
        {/* Main Content */}
        <div className="p-4 pb-0">
          <div className="grid grid-cols-2">
            {/* Left Column - Attributes */}
            <div>Date</div>
            <div>
              <div className="h-12">
                <DatePicker
                  selected={date}
                  onChange={(value) => setDate(value)}
                />
              </div>
            </div>
          </div>

          <div className="grid grid-cols-2">
            {/* Left Column - Attributes */}
            <div>Autogenerated</div>
            <div>
              <Select
                value={isAutoGenerated}
                onChange={(e) => setIsAutoGenerated(e.target.value)}
              >
                <MenuItem value={"false"}>False</MenuItem>
                <MenuItem value={"true"}>True</MenuItem>
              </Select>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 gap-24 bg-brand-BADFCD rounded-b-2xl flex justify-center">
          <button
            onClick={onClose}
            className="px-8 bg-brand-BDC3C0 text-white rounded-full font-medium hover:bg-gray-300 transition-colors duration-200"
          >
            Cancel
          </button>
          <button
            onClick={async () => {
              if (!date) {
                alert("Invalid date!");
                return;
              }
              await onSave({
                date: date.toISOString(),
                is_auto_generated: isAutoGenerated === "true",
              });
            }}
            className="px-8 py-3 bg-emerald-500 text-white rounded-full font-medium hover:bg-emerald-600 transition-colors duration-200"
          >
            Save
          </button>
        </div>
      </div>
    </div>
  );
};

export { AddSchedulePopup };
